version: '3'

services:
  flask-app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask-app
    restart: unless-stopped
    ports:
      - "12345:${APP_PORT}"  # Map host port 12345 to container port defined in APP_PORT
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 4100
      MONGODB_DATABASE: flasktest
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongo-container  # Ensure MongoDB container starts first

  mongo-container: # name of the MongoDB service to be used in pymongo connection string
           # This name can be used as a hostname for inter-container communication within the Docker network created by Docker Compose.
    image: mongo:6.0
    container_name: mongo-container
    restart: unless-stopped
    volumes:
      - ./data:/data/db  # Persist data from the container (/data/db) to the host machine (./data)